verbs = ["Break", "Build", "Buy", "Coach",
         "Color", "Cough", "Create", "Complete",
         "Cry", "Dance", "Describe", "Draw",
         "Drink", "Eat", "Edit", "Enter",
         "Exit", "Imitate", "Invent", "Jump",
         "Laugh", "Lie", "Listen", "Paint",
         "Plan", "Play", "Read", "Replace",
         "Run", "Scream", "See", "Shop",
         "Shout", "Sing", "Skip", "Sleep",
         "Sneeze", "Solve", "Study", "Teach",
         "Touch", "Turn", "Walk", "Win",
         "Write", "Whistle", "Yank", "Zip"
         "Doubt", "Feel", "Forget",
         "Hate", "Hear", "Hope",
         "Impress", "Know", "Learn",
         "Like", "Look", "Love",
         "Mind", "Notice", "Own",
         "Perceive", "Realize", "Recognize",
         "Remember", "See", "Smell",
         "Surprise", "Please", "Prefer",
         "Promise", "Think", "Understand",
         ]

nouns = [
    "Actor", 	"Gold", 	"Painting",
    "Advertisement", 	"Grass", 	"Parrot",
    "Afternoon", 	"Greece", 	"Pencil",
    "Airport", 	"Guitar", 	"Piano",
    "Ambulance", 	"Hair", 	"Pillow",
    "Animal", 	"Hamburger", 	"Pizza",
    "Answer", 	"Helicopter", 	"Planet",
    "Apple", 	"Helmet", 	"Plastic",
    "Army", 	"Holiday", 	"Portugal",
    "Australia", 	"Honey", 	"Potato",
    "Balloon", 	"Horse", 	"Queen",
    "Banana", 	"Hospital", 	"Quill",
    "Battery", 	"House", 	"Rain",
    "Beach", 	"Hydrogen", 	"Rainbow",
    "Beard", 	"Ice", 	"Raincoat",
    "Bed", 	"Insect", 	"Refrigerator",
    "Belgium", 	"Insurance", 	"Restaurant",
    "Boy", 	"Iron", 	"River",
    "Branch", 	"Island", 	"Rocket",
    "Breakfast", 	"Jackal", 	"Room",
    "Brother", 	"Jelly", 	"Rose",
    "Camera", 	"Jewellery", 	"Russia",
    "Candle", 	"Jordan", 	"Sandwich",
    "Car", 	"Juice", 	"School",
    "Caravan", 	"Kangaroo", 	"Scooter",
    "Carpet", 	"King", 	"Shampoo",
    "Cartoon", 	"Kitchen", 	"Shoe",
    "China", 	"Kite", 	"Soccer",
    "Church", 	"Knife", 	"Spoon",
    "Crayon", 	"Lamp", 	"Stone",
    "Crowd", 	"Lawyer", 	"Sugar",
    "Daughter", 	"Leather", 	"Sweden",
    "Death", 	"Library", 	"Teacher",
    "Denmark", 	"Lighter", 	"Telephone",
    "Diamond", 	"Lion", 	"Television",
    "Dinner", 	"Lizard", 	"Tent",
    "Disease", 	"Lock", 	"Thailand",
    "Doctor", 	"London", 	"Tomato",
    "Dog", 	"Lunch", 	"Toothbrush",
    "Dream", 	"Machine", 	"Traffic",
    "Dress", 	"Magazine", 	"Train",
    "Easter", 	"Magician", 	"Truck",
    "Egg", 	"Manchester", 	"Uganda",
    "Eggplant", 	"Market", 	"Umbrella",
    "Egypt", 	"Match", 	"Van",
    "Elephant", 	"Microphone", 	"Vase",
    "Energy", 	"Monkey", 	"Vegetable",
    "Engine", 	"Morning", 	"Vulture",
    "England", 	"Motorcycle", 	"Wall",
    "Evening", 	"Nail", 	"Whale",
    "Eye", 	"Napkin", 	"Window",
    "Family", 	"Needle", 	"Wire",
    "Finland", 	"Nest", 	"Xylophone",
    "Fish", 	"Nigeria", 	"Yacht",
    "Flag", 	"Night", 	"Yak",
    "Flower", 	"Notebook", 	"Zebra",
    "Football", 	"Ocean", 	"Zoo",
    "Forest", 	"Oil", 	"Garden",
    "Fountain", 	"Orange", 	"Gas",
    "France", 	"Oxygen", 	"Girl",
    "Furniture", 	"Oyster", 	"Glass",
    "Garage", 	"Ghost",
]

greeknames = ["Zeus",
              "Poseidon",
              "Ares",
              "Aphrodite",
              "Hera",
              "Demeter",
              "Athena",
              "Apollo",
              "Artemis",
              "Hephaestus",
              "Hermes",
              "Dionysus",
              "Ophelia",
              "Atticus",
              "Theodore",
              "Atlas",
              "Iris",
              "Theo",
              "Daphne",
              "Penelope",
              "Sebastian",
              "Cora",
              "Evangeline",
              "Tobias",
              "Chloe",
              "Phoebe",
              "Lyra",
              "Nico",
              "Thea",
              "Alexander",
              "Anastasia",
              "Elias",
              "Lucas",
              "Elena",
              "Athena",
              "Maya",
              "Orion",
              "Luke",
              "Phoenix",
              "Sophie",
              "Lydia",
              "Alexandra",
              "Persephone",
              "Cosmo",
              "Zephyr",
              "Calliope",
              "Margaret",
              "Sophia",
              "Amara",
              "Andrew",
              "Cynthia",
              "Apollo",
              "Agnes",
              "Lysander",
              "George",
              "Peter",
              "Helena",
              "Althea",
              "Linus",
              "Ariadne",
              "Nicholas",
              "Catherine"]

jobs = [
    "Professional athlete",
    "Electrical Engineer",
    "Statistician",
    "Bookkeeping clerk",
    "Fitness Trainer",
    "HR Specialist",
    "Dental Hygienist",
    "Automotive mechanic",
    "Landscape Architect",
    "Civil Engineer",
    "Respiratory Therapist",
    "Carpenter",
    "Mathematician",
    "Paralegal",
    "Computer Systems Administrator",
    "Clinical Laboratory Technician",
    "Reporter",
    "Registered Nurse",
    "Public Relations Specialist",
    "Janitor",
    "Psychologist",
    "Cost Estimator",
    "Elementary School Teacher",
    "Educator",
    "IT Manager",
    "Sports Coach",
    "Massage Therapist",
    "Plumber",
    "Surveyor",
    "Photographer",
    "Art Director",
    "Dentist",
    "Radiologic Technologist",
    "Electrician",
    "Referee",
    "Economist",
    "Occupational Therapist",
    "Writer",
    "Physician",
    "Construction Manager",
    "Computer Systems Analyst",
    "Artist",
    "Drafter",
    "Hairdresser",
    "Medical Assistant",
    "Cashier",
    "Speech-Language Pathologist",
    "Farmer",
    "Recreational Therapist",
    "Housekeeper",
    "Actuary",
    "Dancer",
    "Medical Secretary",
    "Computer Programmer",
    "Insurance Agent",
    "Physicist",
    "Auto Mechanic",
    "Court Reporter",
    "Librarian",
    "School Counselor",
    "Editor",
    "Budget analyst",
    "Marriage & Family Therapist",
    "Truck Driver",
    "Middle School Teacher",
    "Systems Analyst",
    "Judge",
    "Personal Care Aide",
    "Zoologist",
    "Computer Hardware Engineer",
    "Firefighter",
    "Marketing Manager",
    "Substance Abuse Counselor",
    "Desktop publisher",
    "Software Developer",
    "Customer Service Representative",
    "Chemist",
    "Database administrator",
    "Compliance Officer",
    "School Psychologist",
    "Environmental scientist",
    "Food Scientist",
    "Urban Planner",
    "Historian",
    "Computer Support Specialist",
    "Bus Driver",
    "Anthropologist",
    "Executive Assistant",
    "Patrol Officer",
    "Receptionist",
    "Mechanical Engineer",
    "Security Guard",
    "Preschool Teacher",
    "College Professor",
    "Musician",
    "Veterinarian",
    "Actor",
    "Recreation & Fitness Worker",
    "High School Teacher",
    "Financial Advisor",
    "Diagnostic Medical Sonographer",
    "Police Officer",
    "Loan Officer",
    "Microbiologist",
    "Web Developer",
    "Physical Therapist",
    "Telemarketer",
    "Lawyer",
    "Designer",
    "Coach",
    "Event Planner",
    "Interpreter & Translator",
    "Human Resources Assistant",
    "Chef",
    "Paramedic",
    "Market Research Analyst",
    "Landscaper & Groundskeeper",
    "Real Estate Agent",
    "Accountant",
    "Logistician",
    "Architect",
    "Teacher Assistant",
    "Social Worker",
    "Childcare worker",
    "Epidemiologist",
    "Pharmacist",
    "Maintenance & Repair Worker",
    "Painter",
    "Secretary",
    "Mason",
]
